Repository mattieha/slider-button-card, pull requests merged in 2021-07, with the labels that each got.

#85 chore: add yaml examples to readme
  README.md
  assets/examples/action-custom-icon.png
  assets/examples/action-custom.png
  assets/examples/action-minimal.png
  assets/examples/climate.gif
  assets/examples/cover.gif
  assets/examples/fan.gif
  assets/examples/general-compact.png
  assets/examples/general-minimal.png
  assets/examples/icon-icon-override.png
  assets/examples/icon-minimal.png
  assets/examples/media.gif
  assets/examples/slider-force-square.png
  assets/examples/slider-minimal.png
  assets/examples/slider-show-track.png
  assets/examples/slider-state-color.png
  assets/examples/switch.gif
Labels: documentation

#36 feat: add support for lock entities
  README.md
  assets/examples/lock.gif
  dist/slider-button-card.js
  src/controllers/get-controller.ts
  src/controllers/lock-controller.ts
  src/types.ts
Labels: feature

#88 fix: gradient for ios and css vars on host
  dist/slider-button-card.js
  src/slider-button-card.ts
Labels: bug

#89 chore: add Portuguese language
  README.md
  dist/slider-button-card.js
  src/localize/languages/pt.json
  src/localize/localize.ts
Labels: translation

#96 Add German translation
  README.md
  src/localize/languages/de.json
  src/localize/localize.ts
Labels: translation

#103 Create fr.json
  src/localize/languages/fr.json
Labels: translation
